services:
  - type: web
    name: trading-news-agent
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: ALPHAVANTAGE_API_KEY
        sync: false
      - key: FMP_API_KEY
        sync: false
      - key: NEWSAPI_KEY
        sync: false
      - key: TELEGRAM_CHANNEL_ID
        sync: false
      - key: GITHUB_CALENDAR_CACHE_URL
        value: https://raw.githubusercontent.com/laslodinello-afk/trading_news-bot/main/calendar_cache.json
      - key: FXSTREET_CACHE_URL
        value: https://raw.githubusercontent.com/laslodinello-afk/trading_news-bot/main/fxstreet_cache.json
      - key: TRADING_PAIRS
        value: XAUUSD,EURUSD,GBPUSD,US30,BTCUSD,ETHUSD,DAX,SP500,NASDAQ,BRENT,CAC40
